services:
  # NebulaGraph Test API
  nebulagraph-test-api:
    build: ../../
    container_name: nebulagraph-test-api
    ports:
      - "5090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - nebula-net
    depends_on:
      - dapr-sidecar

  # Dapr sidecar for Test API
  # Dapr sidecar
  dapr-sidecar:
    image: "ghcr.io/dapr/daprd:latest"
    command: [
      "./daprd",
      "--app-id", "nebulagraph-test-api",
      "--app-port", "80",
      "--dapr-http-port", "3002",
      "--dapr-grpc-port", "50002",
      "--components-path", "/components",
      "--config", "/config/config.yaml",
      "--log-level", "debug"
    ]
    env_file:
      - "../../../.env.docker"
    volumes:
      - "../../components:/components"
      - "./config:/config"
    ports:
      - "3002:3002"  # Different port from our pluggable component
      - "50002:50002"
    networks:
      - nebula-net

networks:
  nebula-net:
    external: true
