services:
  # NebulaGraph Dapr Pluggable Component
  nebulagraph-component:
    container_name: nebulagraph-grpc-test-component
    build:
      context: ../../dapr-pluggable-components
      dockerfile: Dockerfile
    environment:
      - DAPR_COMPONENT_SOCKETS_FOLDER=/var/run
    volumes:
      - socket:/var/run
    networks:
      - nebula-net

  # NebulaGraph Test gRPC API
  nebulagraph-test-grpc-api:
    build: .
    container_name: nebulagraph-test-grpc-api
    ports:
      - "${TEST_GRPC_API_HOST_PORT:-5093}:${TEST_GRPC_API_APP_PORT:-80}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${TEST_GRPC_API_APP_PORT:-80}
      - DAPR_HTTP_ENDPOINT=http://nebulagraph-test-grpc-api-sidecar:${TEST_GRPC_API_HTTP_PORT:-3503}
      - DAPR_GRPC_ENDPOINT=http://nebulagraph-test-grpc-api-sidecar:${TEST_GRPC_API_GRPC_PORT:-50003}
    env_file:
      - "../../.env"
    networks:
      - nebula-net
    depends_on:
      - nebulagraph-test-grpc-api-sidecar

  # Dapr sidecar for Test gRPC API
  nebulagraph-test-grpc-api-sidecar:
    image: "ghcr.io/dapr/daprd:latest"
    container_name: nebulagraph-test-grpc-api-sidecar
    command: [
      "./daprd",
      "--app-id", "nebulagraph-test",
      "--app-port", "${TEST_GRPC_API_APP_PORT:-80}",
      "--app-protocol", "grpc",
      "--dapr-http-port", "${TEST_GRPC_API_HTTP_PORT:-3503}",
      "--dapr-grpc-port", "${TEST_GRPC_API_GRPC_PORT:-50003}",
      "--components-path", "/components",
      "--config", "/components/config.yaml",
      "--log-level", "debug"
    ]
    environment:
      - DAPR_COMPONENTS_SOCKETS_FOLDER=/var/run
    env_file:
      - "../../.env"
    depends_on:
      - nebulagraph-component
    volumes:
      - socket:/var/run
      - "../../components:/components:ro"
      - "../../secrets:/secrets:ro"
    ports:
      - "${TEST_GRPC_API_HTTP_PORT:-3503}:${TEST_GRPC_API_HTTP_PORT:-3503}"
      - "${TEST_GRPC_API_GRPC_PORT:-50003}:${TEST_GRPC_API_GRPC_PORT:-50003}"
    networks:
      - nebula-net

volumes:
  socket:

networks:
  nebula-net:
    external: true
