apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nebulagraph-store
spec:
  type: state.nebulagraph
  version: v1
  metadata:
  - name: graphHost
    value: "127.0.0.1"
  - name: graphPort
    value: "9669"
  - name: space
    value: "dapr_state"
  - name: username
    value: "root"
  - name: password
    value: "nebula"
  - name: tag
    value: "state_tag"
