# Copyright 2022 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  # ScyllaDB Primary Node
  scylladb-node1:
    image: scylladb/scylla:${SCYLLA_VERSION:-5.4.6}
    container_name: ${SCYLLA_NODE1_CONTAINER:-scylladb-node1}
    restart: unless-stopped
    ports:
      - "${SCYLLA_CQL_PORT:-9042}:9042"      # CQL Native Protocol
      - "${SCYLLA_JMX_PORT:-7199}:7199"      # JMX
      - "${SCYLLA_REST_PORT:-10000}:10000"    # REST API
      - "${SCYLLA_PROMETHEUS_PORT:-9180}:9180"      # Prometheus metrics
      - "${SCYLLA_INTER_NODE_PORT:-7002}:7000"      # Inter-node communication
      - "${SCYLLA_SSL_INTER_NODE_PORT:-7003}:7001"      # SSL Inter-node communication
    volumes:
      - scylla-data-node1:/var/lib/scylla
      - scylla-config:/etc/scylla
    networks:
      - nebula-net
    command: 
      - --seeds=${SCYLLA_NODE1_CONTAINER:-scylladb-node1}
      - --smp=${SCYLLA_SMP:-1}
      - --memory=${SCYLLA_MEMORY:-1G}
      - --overprovisioned=1
      - --api-address=0.0.0.0
      - --listen-address=0.0.0.0
      - --rpc-address=0.0.0.0
      - --broadcast-address=${SCYLLA_NODE1_CONTAINER:-scylladb-node1}
      - --broadcast-rpc-address=${SCYLLA_NODE1_CONTAINER:-scylladb-node1}
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

  # ScyllaDB Web Console (optional)
  scylla-manager:
    image: scylladb/scylla-manager:${SCYLLA_MANAGER_VERSION:-3.2.6}
    container_name: ${SCYLLA_MANAGER_CONTAINER:-scylla-manager}
    restart: unless-stopped
    ports:
      - "${SCYLLA_MANAGER_WEB_PORT:-7004}:5080"      # Manager Web UI (using 7004 to avoid conflict with node inter-communication port)
      - "${SCYLLA_MANAGER_API_PORT:-5091}:5090"      # Manager API
    environment:
      - SCYLLA_MANAGER_DB_HOSTS=${SCYLLA_NODE1_CONTAINER:-scylladb-node1}:${SCYLLA_CQL_PORT:-9042}
    networks:
      - nebula-net
    depends_on:
      - scylladb-node1
    volumes:
      - scylla-manager-data:/etc/scylla-manager

volumes:
  scylla-data-node1:
  scylla-config:
  scylla-manager-data:

networks:
  nebula-net:
    external: true
    name: ${NEBULA_NETWORK_NAME:-nebula-net}
