apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nebulagraph-state
  namespace: default
spec:
  type: state.nebulagraph-state
  version: v1
  metadata:
  - name: hosts
    secretKeyRef:
      name: nebulagraph:host
      key: nebulagraph:host
  - name: port
    secretKeyRef:
      name: nebulagraph:port
      key: nebulagraph:port
  - name: username
    secretKeyRef:
      name: nebulagraph:username
      key: nebulagraph:username
  - name: password
    secretKeyRef:
      name: nebulagraph:password
      key: nebulagraph:password
  - name: space
    secretKeyRef:
      name: nebulagraph:space
      key: nebulagraph:space
  
  # Configuration with secret references
  - name: connectionTimeout
    secretKeyRef:
      name: nebulagraph:connectionTimeout
      key: nebulagraph:connectionTimeout
  - name: executionTimeout
    secretKeyRef:
      name: nebulagraph:executionTimeout
      key: nebulagraph:executionTimeout
auth:
  secretStore: local-secret-store
