apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nebulagraph-state
  namespace: default
spec:
  type: state.nebulagraph-state
  version: v1
  secretStores:
  - "local-secret-store"
  metadata:
  - name: hosts
    secretKeyRef:
      name: nebulagraph:host
      key: nebulagraph:host
  - name: port
    secretKeyRef:
      name: nebulagraph:port
      key: nebulagraph:port
  - name: username
    secretKeyRef:
      name: nebulagraph:username
      key: nebulagraph:username
  - name: password
    secretKeyRef:
      name: nebulagraph:password
      key: nebulagraph:password
  - name: space
    secretKeyRef:
      name: nebulagraph:space
      key: nebulagraph:space
  
  # Connection pool configuration with secret references
  - name: connectionTimeout
    secretKeyRef:
      name: nebulagraph:connectionTimeout
      key: nebulagraph:connectionTimeout
  - name: executionTimeout
    secretKeyRef:
      name: nebulagraph:executionTimeout
      key: nebulagraph:executionTimeout
  - name: maxConnPoolSize
    secretKeyRef:
      name: nebulagraph:maxConnPoolSize
      key: nebulagraph:maxConnPoolSize
  - name: minConnPoolSize
    secretKeyRef:
      name: nebulagraph:minConnPoolSize
      key: nebulagraph:minConnPoolSize
  - name: idleTime
    secretKeyRef:
      name: nebulagraph:idleTime
      key: nebulagraph:idleTime
auth:
  secretStore: local-secret-store
