apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nebulagraph-state
  namespace: default
spec:
  type: state.nebulagraph-state
  version: v1
  secretStores:
  - "local-secret-store"
  metadata:
  - name: hosts
    value: "${NEBULA_HOST:-nebula-graphd}"
  - name: port
    value: "${NEBULA_PORT:-9669}"
  - name: username
    secretKeyRef:
      name: nebulagraph:username
      key: nebulagraph:username
  - name: password
    secretKeyRef:
      name: nebulagraph:password
      key: nebulagraph:password
  - name: space
    value: "${NEBULA_SPACE:-dapr_state}"
  - name: connectionTimeout
    value: "${NEBULA_CONNECTION_TIMEOUT:-10s}"
  - name: executionTimeout
    value: "${NEBULA_EXECUTION_TIMEOUT:-30s}"
  - name: maxConnPoolSize
    value: "${NEBULA_MAX_CONN_POOL_SIZE:-50}"
  - name: minConnPoolSize
    value: "${NEBULA_MIN_CONN_POOL_SIZE:-5}"
  - name: idleTime
    value: "${NEBULA_IDLE_TIME:-8h}"
