apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nebulagraph-state
  namespace: default
spec:
  type: state.nebulagraph-state
  version: v1
  metadata:
  - name: hosts
    value: "${NEBULA_HOST}"
  - name: port
    value: "${NEBULA_PORT}"
  - name: username
    value: "${NEBULA_USERNAME}"
  - name: password
    value: "${NEBULA_PASSWORD}"
  - name: space
    value: "${NEBULA_SPACE}"
  
  # Configuration with environment variable support
  - name: connectionTimeout
    value: "${NEBULA_CONNECTION_TIMEOUT}"
  - name: executionTimeout
    value: "${NEBULA_EXECUTION_TIMEOUT}"
