apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nebulagraph-state
  namespace: default
spec:
  type: state.nebulagraph-state
  version: v1
  metadata:
  - name: hosts
    value: "${NEBULA_HOST:-localhost}"
  - name: port
    value: "${NEBULA_PORT:-9669}"
  - name: username
    value: "${NEBULA_USERNAME:-root}"
  - name: password
    value: "${NEBULA_PASSWORD:-nebula}"
  - name: space
    value: "${NEBULA_SPACE:-dapr_state}"
  
  # Configuration with environment variable support
  - name: connectionTimeout
    value: "${NEBULA_CONNECTION_TIMEOUT:-10s}"
  - name: executionTimeout
    value: "${NEBULA_EXECUTION_TIMEOUT:-30s}"
