apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: redis:host
      key: redis:host
  - name: redisPassword
    secretKeyRef:
      name: redis:password
      key: redis:password
  - name: redisDB
    secretKeyRef:
      name: redis:db
      key: redis:db
  
  # Connection and retry configuration
  - name: maxRetries
    secretKeyRef:
      name: redis:maxRetries
      key: redis:maxRetries
  - name: maxRetryBackoff
    secretKeyRef:
      name: redis:maxRetryBackoff
      key: redis:maxRetryBackoff
  - name: dialTimeout
    secretKeyRef:
      name: redis:dialTimeout
      key: redis:dialTimeout
  - name: readTimeout
    secretKeyRef:
      name: redis:readTimeout
      key: redis:readTimeout
  - name: writeTimeout
    secretKeyRef:
      name: redis:writeTimeout
      key: redis:writeTimeout
  
  # Connection pooling for performance
  - name: poolSize
    secretKeyRef:
      name: redis:poolSize
      key: redis:poolSize
  - name: poolTimeout
    secretKeyRef:
      name: redis:poolTimeout
      key: redis:poolTimeout
  - name: maxConnAge
    secretKeyRef:
      name: redis:maxConnAge
      key: redis:maxConnAge
  - name: idleTimeout
    secretKeyRef:
      name: redis:idleTimeout
      key: redis:idleTimeout
  - name: idleCheckFrequency
    secretKeyRef:
      name: redis:idleCheckFrequency
      key: redis:idleCheckFrequency
  
  # Pub/Sub specific settings
  - name: redeliverInterval
    secretKeyRef:
      name: redis:redeliverInterval
      key: redis:redeliverInterval
  - name: processingTimeout
    secretKeyRef:
      name: redis:processingTimeout
      key: redis:processingTimeout
  - name: redisType
    secretKeyRef:
      name: redis:type
      key: redis:type
  - name: enableTLS
    secretKeyRef:
      name: redis:enableTLS
      key: redis:enableTLS
auth:
  secretStore: local-secret-store
