apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: "${REDIS_HOST}"
  - name: redisPassword
    value: "${REDIS_PASSWORD}"
  - name: redisDB
    value: "${REDIS_DB}"
  
  # Connection and retry configuration
  - name: maxRetries
    value: "${REDIS_MAX_RETRIES}"
  - name: maxRetryBackoff
    value: "${REDIS_MAX_RETRY_BACKOFF}"
  - name: dialTimeout
    value: "${REDIS_DIAL_TIMEOUT}"
  - name: readTimeout
    value: "${REDIS_READ_TIMEOUT}"
  - name: writeTimeout
    value: "${REDIS_WRITE_TIMEOUT}"
  
  # Connection pooling for performance
  - name: poolSize
    value: "${REDIS_POOL_SIZE}"
  - name: poolTimeout
    value: "${REDIS_POOL_TIMEOUT}"
  - name: maxConnAge
    value: "${REDIS_MAX_CONN_AGE}"
  - name: idleTimeout
    value: "${REDIS_IDLE_TIMEOUT}"
  - name: idleCheckFrequency
    value: "${REDIS_IDLE_CHECK_FREQUENCY}"
  
  # Pub/Sub specific settings
  - name: redeliverInterval
    value: "${REDIS_REDELIVER_INTERVAL}"
  - name: processingTimeout
    value: "${REDIS_PROCESSING_TIMEOUT}"
  - name: redisType
    value: "${REDIS_TYPE}"
  - name: enableTLS
    value: "${REDIS_ENABLE_TLS}"
