apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: scylladb-state
  namespace: default
spec:
  type: state.scylladb-state
  version: v1
  metadata:
  - name: hosts
    secretKeyRef:
      name: scylladb:hosts
      key: scylladb:hosts
  - name: port
    secretKeyRef:
      name: scylladb:port
      key: scylladb:port
  - name: username
    secretKeyRef:
      name: scylladb:username
      key: scylladb:username
  - name: password
    secretKeyRef:
      name: scylladb:password
      key: scylladb:password
  - name: keyspace
    secretKeyRef:
      name: scylladb:keyspace
      key: scylladb:keyspace
  - name: table
    secretKeyRef:
      name: scylladb:table
      key: scylladb:table
  - name: consistency
    secretKeyRef:
      name: scylladb:consistency
      key: scylladb:consistency
  - name: connectionTimeout
    secretKeyRef:
      name: scylladb:connectionTimeout
      key: scylladb:connectionTimeout
  - name: socketKeepalive
    secretKeyRef:
      name: scylladb:socketKeepalive
      key: scylladb:socketKeepalive
  - name: maxReconnectInterval
    secretKeyRef:
      name: scylladb:maxReconnectInterval
      key: scylladb:maxReconnectInterval
  - name: numConns
    secretKeyRef:
      name: scylladb:numConns
      key: scylladb:numConns
  - name: disableInitialHostLookup
    secretKeyRef:
      name: scylladb:disableInitialHostLookup
      key: scylladb:disableInitialHostLookup
  - name: replicationStrategy
    secretKeyRef:
      name: scylladb:replicationStrategy
      key: scylladb:replicationStrategy
  - name: replicationFactor
    secretKeyRef:
      name: scylladb:replicationFactor
      key: scylladb:replicationFactor
auth:
  secretStore: local-secret-store
